config_bets = {
    "Paris spéciaux": {
        "Paris spéciaux buteur": False,
        "Coup franc direct marqué dans le match": False,
        "Y aura-t-il un but de la tête dans le match ?": False,
    },
    "Fun Bets": {
        "Fun Bets": False
    },
    "2ème MT": {
        "2e Mi-temps - Résultat": False,
        "2e Mi-temps - Première équipe à marquer": False,
        "2e Mi-temps - Chance double": False,
        "2e Mi-temps - Résultat hors match nul": False,
        "2e Mi-temps - Ecart entre les équipes": False,
        "2e Mi-temps - Total de buts": False,
        "2e Mi-temps - Total de buts - Equipe à domicile": False,
        "2e Mi-temps - Total de buts - Equipe à l'extérieur": False,
        "2e Mi-temps - Nombre exact de buts": False,
        "2e Mi-temps - Total de buts multichoix": False,
        "2e Mi-temps - Les 2 équipes marquent": False,
        "2e Mi-temps - L'équipe à domicile n'encaisse pas de but": False,
        "2e Mi-temps - L'équipe à l'extérieur n'encaisse pas de but": False,
        "2e Mi-temps - Combo résultat & Les 2 équipes marquent": False,
        "2e Mi-temps - Combo résultat & Total de buts": False,
        "2e Mi-temps - Combo chance double & Les 2 équipes marquent": False,
    },
    "Buteurs": {
        "Buteur": True,
        "Buteur (remboursé si non titulaire)": False,
        "Buteur chance double": False,
        "Buteur chance triple": False,
        "Les 2 joueurs marquent dans le match": False,
        "Les 3 joueurs marquent dans le match": False,
        "Le joueur marque 2 buts ou +": False,
        "Le joueur marque 3 buts ou +": False,
        "Le joueur marque 4 buts ou +": False,
        "1er buteur": False,
        "Combo buteur & son équipe gagne": False,
        "Combo buteur & match nul": False,
        "Combo buteur & l'équipe adverse gagne": False,
        "Combo buteur & plus de 1,5 buts": False,
        "Combo buteur & plus de 2,5 buts": False,
        "Combo buteur & plus de 3,5 buts": False,
        "Combo buteur & moins de 1,5 buts": False,
        "Combo buteur & moins de 2,5 buts": False,
        "Combo buteur & moins de 3,5 buts": False,
        "Combo buteur & plus de 4,5 buts": False,
        "Combo buteur & plus de 5,5 buts": False,
        "Combo buteur & les deux équipes marquent": False,
        "Combo buteur & l'équipe adverse ne marque pas": False,
        "Face à face buteur contre équipe adverse (remboursé si non titulaire)": False,
        "Un remplaçant marquera un but": False,
        "1er buteur chance double": False,
        "Dernier buteur": False,
        "1er ou dernier buteur": False,
        "Combo 1er buteur & son équipe gagne": False,
        "Combo 1er buteur & match nul": False,
        "Combo 1er buteur & l'équipe adverse gagne": False
    },
    "Compétition": {
        "Vainqueur de la compétition": False,
        "Vainqueur de la compétition - Chance double": False,
        "Vainqueur du groupe": False,
        "Compétition : Meilleur buteur": False,
        "Equipe Qualifiée pour la Finale": False,
        "Vainqueur sans FC Barcelone et Real Madrid": False,
        "Vainqueur sans le Bayern Munich": False,
        "Vainqueur sans le PSG": False,
        "Qui finira dans les deux premiers ?": False,
        "Podium de la compétition": False,
        "Qui finira dans les 4 premiers": False,
        "Qui finira dans les 5 premiers": False,
        "Top 6": False,
        "Top 10": False,
        "Quelle équipe sera promue": False,
        "Quelle équipe sera reléguée": False
    },
    "1ère MT": {
        "1ère Mi-temps - Résultat": False,
        "Mi-temps - Equipe à l'extérieur - Total de buts": False,
        "Mi-temps - Total de buts": False,
        "1ère Mi-temps - Total de buts": False,
        "Mi-temps - Chance double": False,
        "Mi-temps - Ecart entre équipes": False,
        "Mi-Temps - Les 2 équipes marquent": False,
        "Mi-temps - Nombre exact de buts": False,
        "Mi-temps - Score exact": False,
        "Mi-temps - Résultat hors match nul": False,
        "Mi-temps - Equipe à domicile - Total de buts": False,
        "Mi-temps - Qui marquera en 1er": False,
        "1ère Mi-temps - Combo chance double & les 2 équipes marquent": False,
        "1ère Mi-temps - Chance double": False,
        "1ère Mi-temps - Résultat hors match nul": False,
        "1ère Mi-temps - Ecart entre les équipes": False,
        "1ère Mi-temps - Première équipe à marquer": False,
        "1ère Mi-temps - Total de buts - Equipe à domicile": False,
        "1ère Mi-temps - Total de buts - Equipe à l'extérieur": False,
        "1ère Mi-temps - Nombre exact de buts": False,
        "1ère Mi-temps - Total de buts multichoix": False,
        "1ère Mi-temps - Les 2 équipes marquent": False,
        "1ère Mi-temps - L'équipe à domicile n'encaisse pas de but": False,
        "1ère Mi-temps - L'équipe à l'extérieur n'encaisse pas de but": False,
        "1ère Mi-temps - Combo résultat & Les 2 équipes marquent": False,
        "1ère Mi-temps - Combo Résultat & Total de buts": False,
        "1ère Mi-temps - Score exact": False
    },
    "Buts par équipe": {
        "Total de buts - Equipe à domicile": False,
        "Total de buts - Equipe à l'extérieur": False,
        "Nombre exact de buts de l'équipe à domicile": False,
        "Nombre exact de buts de l'équipe à l'extérieur": False,
        "Total de buts multichoix - Equipe à domicile": False,
        "Total de buts multichoix - Equipe à l'extérieur": False,
        "Mi-temps avec le + de buts - Equipe à domicile": False,
        "Mi-temps avec le + de buts - Equipe à l'extérieur": False
    },
    "Scores": {
        "Score exact": False,
        "Score Exact - Multichoix": False,
        "Mi-temps / Fin de match - Score exact": False
    },
    "Résultat": {
        "Résultat du match": "WIN_DRAW_LOSE",
        "Qualification": False,
        "Type de Qualification": False,
        "Chance double": False,
        "Ecart entre équipes": False,
        "Combo résultat du match & Les 2 équipes marquent": False,
        "Combo résultat du match & total de buts": False,
        "Combo résultat du match & Total de buts": False,
        "Résultat du match (remboursé si match nul)": False,
        "Combo chance double & les 2 équipes marquent": False,
        "Mi-temps / Fin de match": False,
        "Qui marquera en 1er": False,
        "Gagnera en ne concédant aucun but": False,
        "Remporte les 2 Mi-temps": False,
        "Remporte l'une des Mi-temps": False,
        "Résultat (remboursé si l'équipe à domicile gagne)": False,
        "Résultat (remboursé si l'équipe à l'extérieur gagne)": False,
        "Marge du vainqueur": False,
        "L'équipe à domicile gagne sans prendre de but": False,
        "L'équipe à l'extérieur gagne sans prendre de but": False,
        "L'équipe à domicile gagne les 2 Mi-temps": False,
        "L'équipe à l'extérieur gagne les 2 Mi-temps": False,
        "L'équipe à domicile gagne au moins 1 Mi-temps": False,
        "L'équipe à l'extérieur gagne au moins 1 Mi-temps": False,
        "Tirs aux buts Oui/Non": False,
        "Prolongations Oui/Non": False,
        "L'équipe à domicile gagne OU + de 2,5 buts dans le match": False,
        "L'équipe à domicile gagne OU - de 2,5 buts dans le match": False,
        "Match nul OU + de 2,5 buts dans le match": False,
        "Match nul OU - de 2,5 buts dans le match": False,
        "L'équipe à l'extérieur gagne OU + de 2,5 buts dans le match": False,
        "L'équipe à l'extérieur gagne OU - de 2,5 buts dans le match": False,
        "L'équipe à domicile gagne OU les 2 équipes marquent": False,
        "Match nul OU les 2 équipe marquent": False,
        "L'équipe à l'extérieur gagne OU les 2 équipes marquent": False,
        "L'équipe à l'extérieur gagne": False,
        "L'équipe à domicile gagne": False,
        "Une des deux équipes gagne": False
    },
    "Buts": {
        "Total de buts": False,
        "But pour les 2 équipes": False,
        "But sur penalty": False,
        "Nombre de buts": False,
        "Qui marquera le 1er but": False,
        "Score in Both Halves": False,
        "Aucun but concédé": False,
        "Dernière équipe à marquer": False,
        "Equipe à domicile - Nombre de buts": False,
        "Equipe à domicile - Total de buts": False,
        "Equipe à l'extérieur - Nombre de buts": False,
        "Equipe à l'extérieur - Total de buts": False,
        "L'équipe à domicile marquera-t-elle un but ?": False,
        "L'équipe à l'extérieur marquera-t-elle un but ?": False,
        "L'équipe à domicile ne concède aucun but": False,
        "L'équipe à l'extérieur ne concède aucun but": False,
        "Mi-temps la plus prolifique": False,
        "Nombre exact de buts": False,
        "Total de buts multichoix": False,
        "Total de buts (intervalle)": False,
        "Plus de 1,5 buts dans les 2 Mi-temps": False,
        "Moins de 1,5 buts dans les 2 Mi-temps": False,
        "L'équipe à domicile n'encaisse pas de but": False,
        "L'équipe à l'extérieur n'encaisse pas de but": False,
        "Les 2 équipes marquent en 1ère Mi-temps / 2e Mi-temps": False,
        "L'équipe à domicile marque dans les 2 Mi-temps": False,
        "L'équipe à l'extérieur marque dans les 2 Mi-temps": False,
        "L'équipe à domicile gagne OU au moins une cage inviolée": False,
        "Match nul OU au moins une cage inviolée": False,
        "L'équipe à l'extérieur gagne OU au moins une cage inviolée": False
    },
    "Minutes": {
        "Minute du 1er but (15 min)": False,
        "Minute du 1er but (10 min)": False,
        "Quel joueur marquera entre la minute 00:00 & 15:00": False,
        "Quel joueur marquera entre la minute 15:01 & 30:00": False,
        "Quel joueur marquera entre la minute 30:01 & la Mi-temps": False,
        "Quel joueur marquera entre la minute 45:01 & 60:00": False,
        "Quel joueur marquera entre la minute 60:01 & 75:00": False,
        "Quel joueur marquera entre la minute 75:01 & la fin du temps réglementaire": False
    },
    "Combo": {
        "Combo résultat du match & les 2 équipes marquent": False,
        "Première équipe à marquer & Résultat du match": False,
        "Combo chance double & total de buts": False,
        "Combo chance double & Total de buts": False,
        "Combo chance double & les 2 équipes marquent": False,
        "Combo total de buts & Les 2 équipes marquent": False,
        "Combo résultat du match & première équipe à marquer": False,
        "Combo chance double (match) & Les 2 équipes marquent en 1ère Mi-temps": False,
        "Combo chance double (match) & Les 2 équipes marquent en 2e Mi-temps": False,
        "Mi-temps / Fin de match & Total de buts": False,
        "Mi-Temps / Fin de match & Total de buts en 1ère Mi-temps": False,
        "Mi-temps / Fin de match & Total de buts (exact)": False
    }
}